  CREATE TABLE "DASHBOARDS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"OWNER_USER_ID" VARCHAR2(100), 
	"IS_PUBLIC" CHAR(1) DEFAULT 'N', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CHECK (IS_PUBLIC IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE INDEX "IDX_DASHBOARDS_OWNER" ON "DASHBOARDS" ("OWNER_USER_ID") 
  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "DASHBOARDS_BIU" 
BEFORE UPDATE ON DASHBOARDS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
ALTER TRIGGER "DASHBOARDS_BIU" ENABLE;
